/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#0b151e',
        foreground: '#d1d5ea',
        border: {
          DEFAULT: '#2c3b4e',
          subtle: '#2c3b4e',
          medium: '#2c3b4e',
          bright: '#1156ae',
        },
        ring: '#1156ae',
        bg: {
          primary: '#0b151e',
          secondary: '#17202e',
          tertiary: '#1a2433',
          overlay: '#1a2737',
        },
        text: {
          primary: '#d1d5ea',
          secondary: '#c7cce1',
          muted: '#b8bbd6',
          inverse: '#0b151e',
        },
        accent: {
          DEFAULT: '#2c3b4e',
          primary: '#1156ae',
          'primary-light': '#d8e9fd',
          secondary: '#1c395e',
          'secondary-light': '#2c3b4e',
          success: '#22c55e',
          'success-light': '#bbf7d0',
          warning: '#e88930',
          'warning-light': '#db57c3',
          danger: '#ba1c1e',
          'danger-light': '#ffffff',
          xp: '#db57c3',
        },
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
        xxxl: '32px',
        huge: '48px',
        massive: '64px',
      },
      borderRadius: {
        sm: '5.6px',
        md: '7.6px',
        lg: '9.6px',
        xl: '13.6px',
        xxl: '24px',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Poppins', 'sans-serif'],
        serif: ['Libre Baskerville', 'serif'],
        mono: ['Space Mono', 'monospace'],
      },
      fontSize: {
        xs: ['11px', { lineHeight: '16px' }],
        sm: ['13px', { lineHeight: '18px' }],
        md: ['15px', { lineHeight: '20px' }],
        lg: ['17px', { lineHeight: '24px' }],
        xl: ['20px', { lineHeight: '28px' }],
        xxl: ['24px', { lineHeight: '32px' }],
        xxxl: ['32px', { lineHeight: '40px' }],
        hero: ['40px', { lineHeight: '48px' }],
        display: ['48px', { lineHeight: '56px' }],
      },
    },
  },
  plugins: [],
};
